=== tane994/ODH_Project/pp_201920_maninettitanesini-master/src/main/resources/activity_schema.json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"title": "activity",
"description": "activities retrieved from site",
"type": [
"object",
"null"
],
"properties": {
"id": {
"description": "activity's ID",
"type": [
"string",
"null"
]
},
"name": {
"description": "Activity's name",
"type": [
"string",
"null"
]
},
"description": {
"description": "Description",
"type": [
"string",
"null"
]
},
"types": {
"description": "types of activities",
"type": "array",
"items": {
"type": [
"string",
"null"
]

}
},
"hasGPSTrack": {
"description": "is the location GPS tracked?",
"type": [
"boolean",
"null"
]
},
"region": {
"description": "Region of activity",
"type": [
"string",
"null"
]
}
},
"additionalProperties": false
}

=== tane994/ODH_Project/pp_201920_maninettitanesini-master/src/result/Activity01CFEFF8DA586E548327E539276C42F3.json
{
  "id" : "01CFEFF8DA586E548327E539276C42F3",
  "name" : "01 Cross Country Stadio Track Dobbiaco/Toblach",
  "description" : "Demanding round-trip tours starting at the cross-country stadium in Dobbiaco, often used as training tracks by various national cross-country teams from all over the world.This trail will be floodlit on Monday and Thursday from 5:00 pm to 8:00 pm from. Use is subject to a fee.",
  "types" : [ "loipen", "klassisch und skating" ],
  "hasGPSTrack" : true,
  "region" : "D2633A1FC24E11D18F1B006097B8970B"
}
